Remove anything that gave me a hard time

diff --git a/bin/w_fluxanl b/bin/w_fluxanl
--- a/bin/w_fluxanl
+++ b/bin/w_fluxanl
@@ -1,1 +1,61 @@
-west
+#!/bin/bash
+
+# Copyright (C) 2013 Matthew C. Zwier and Lillian T. Chong
+#
+# This file is part of WESTPA.
+#
+# WESTPA is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# WESTPA is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with WESTPA.  If not, see <http://www.gnu.org/licenses/>.
+
+# If $WEST_ROOT is not set, then set it based on the path to this script
+if [ -z "$WEST_ROOT" ]; then
+    export WEST_ROOT=$(python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' $0/../..)
+fi
+
+# We've moved the actual environment variable setting into another script.
+source $WEST_ROOT/bin/w_env
+
+# Take the name of the script to execute from the name by which this process
+# is called (i.e. appropriately-named symlinks to this script work).
+SCRIPT=$(basename $0)
+
+# Find where the requested script is stashed
+if [ "$SCRIPT" == "west" ] ; then
+    FULLSCRIPT=""
+elif [ -e "$WEST_ROOT/lib/west_tools/${SCRIPT}.py" ] ; then
+    FULLSCRIPT="$WEST_ROOT/lib/west_tools/${SCRIPT}.py"
+elif [ -e "$WEST_ROOT/lib/cmds/${SCRIPT}.py" ] ; then
+    FULLSCRIPT="$WEST_ROOT/lib/cmds/${SCRIPT}.py"
+else
+    echo "script ${SCRIPT}.py not found"
+    exit 1
+fi
+
+if [ "$1" == "--profile" ]; then
+    shift
+    pfile=west_profile_$$.dat
+    echo >&2 "Saving profiling information to $pfile"
+    $WEST_PYTHON -m cProfile -o $pfile $FULLSCRIPT "$@"
+    $WEST_PYTHON -c "import sys, pstats; ps = pstats.Stats('$pfile', stream=sys.stderr); ps.sort_stats('time').print_stats(100);"
+elif [ "$1" == "--lprofile" ]; then
+    shift
+    pfile=west_lprofile_$$.dat
+    echo >&2 "Saving line_profiler information to $pfile"
+    $WEST_KERNPROF -l -o $pfile -v $FULLSCRIPT "$@"
+elif [ "$1" == "--strace" ]; then
+    shift
+    echo >&2 "Running $SCRIPT under strace"
+    strace $WEST_PYTHON $FULLSCRIPT "$@"
+else
+    exec $WEST_PYTHON $FULLSCRIPT "$@"
+fi
